---
# handlers file for nifi

- name: reload systemctl
  command: systemctl daemon-reload
  ignore_errors: True  

- name: restart nifi
  service: name=nifi state=restarted enabled=yes
  when: nifi_perform_restart
  ignore_errors: True  
